version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - mvn -v
      - mvn install
      - pwd
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - webapp/target/webapp.war
